name: build

on:
  push: {}
  pull_request: {}
  workflow_dispatch: {}

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ruby
          bundler-cache: true
      - run: bundle exec rubocop
  test:
    needs: lint
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - ruby: "2.5"
            gemfile: "2.5"
          - ruby: "2.6"
            gemfile: "2.6"
          - ruby: "2.7"
            gemfile: "2.7"
          - ruby: "3.0"
            gemfile: "3.0"
          - ruby: "3.1"
            gemfile: "3.1"
          - ruby: "3.2"
            gemfile: "3.2"
          - ruby: "3.3"
            gemfile: "3.3"
          - ruby: "3.4"
            gemfile: "3.4"
          - ruby: "4.0"
            gemfile: "4.0"
          - ruby: "jruby-9.3"
            gemfile: "jruby_9.3"
          - ruby: "jruby-9.4"
            gemfile: "jruby_9.4"
          - ruby: "jruby-10.0"
            gemfile: "jruby_10.0"
    env:
      BUNDLE_GEMFILE: gemfiles/crawler_detect_${{ matrix.gemfile }}.gemfile
    name: Ruby ${{ matrix.ruby }}, test-group ${{ matrix.test-group }}
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: false
      - name: install dependencies
        run: bundle install --jobs 4 --retry 3
      - name: test
        run: bundle exec rspec
  push:
    # Run on push to master branch
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    name: Push gem to RubyGems.org
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ruby
          bundler-cache: true
      - uses: rubygems/release-gem@v1
